"""Add relationship between study blocks, user and course

Revision ID: 667ef0849200
Revises: 5db2046726b8
Create Date: 2021-03-27 16:02:12.767408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667ef0849200'
down_revision = '5db2046726b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_block', sa.Column('course_id', sa.String(length=7), nullable=True))
    op.add_column('study_block', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_block', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'study_block', 'course', ['course_id'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_block', type_='foreignkey')
    op.drop_constraint(None, 'study_block', type_='foreignkey')
    op.drop_column('study_block', 'user_id')
    op.drop_column('study_block', 'course_id')
    # ### end Alembic commands ###
