"""empty message

Revision ID: 6b5e14efa2e9
Revises: 
Create Date: 2021-03-23 23:06:54.283831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5e14efa2e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'full_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('article', 'link',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('article', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('course', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('course_of_study', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('course_of_study', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('course', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('course', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('article', 'link',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('article', 'full_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
