"""empty message

Revision ID: c9bbabc69f61
Revises: fc2a1ab906e1
Create Date: 2021-03-27 17:24:26.492449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bbabc69f61'
down_revision = 'fc2a1ab906e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'session', ['start_time', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    # ### end Alembic commands ###
