"""Change name of course foreign key on session

Revision ID: fc2a1ab906e1
Revises: 43fce954a6ae
Create Date: 2021-03-27 17:04:10.703311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2a1ab906e1'
down_revision = '43fce954a6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('course_code', sa.String(length=7), nullable=True))
    op.drop_constraint('session_course_id_fkey', 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'course', ['course_code'], ['code'])
    op.drop_column('session', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('course_id', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key('session_course_id_fkey', 'session', 'course', ['course_id'], ['code'])
    op.drop_column('session', 'course_code')
    # ### end Alembic commands ###
